### ISSUE TITLE
Trying to set minimum length of text field

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/field_validation#5] opened 2020-03-14 10:35 UTC
@jenlampton OK, in another experiment (which is based upon my use case), I created a new content type with a simple text field. 

I created one validation rule for the text field. Settings:

1) Validator = length
2) Minimum length = 10
3) Maximum length = blank
4) Column = value (also tried format)

I don't really understand the column setting.

I saved this and then tried to create a node. I was able to create the node without problem, despite  only putting in 4-5 characters in that field. I did get this error:

`Notice: Trying to get property 'settings' of non-object in field_validation_length_validator->validate() (line 12 of /var/www/.../.../src/modules/triplo/field_validation/includes/field_validation_length_validator.inc).`

Also these: https://github.com/backdrop-contrib/field_validation/issues/4

**Comment by jenlampton** [comment] 2024-08-12 16:52
I think this is a duplicate of https://github.com/backdrop-contrib/field_validation/issues/3

**Closed as completed by jenlampton** 2024-08-12 16:52 UTC
